#!/bin/bash
# regenerate openerp postgres password

#PASSWORD="openerp"	
PASSWORD=$(mcookie)

CONF=/etc/openerp-server.conf
sed -i "s/db_password =\(.*\)/db_password = $PASSWORD/g" $CONF

/usr/lib/di-live.d/??pgsql-password -u openerp -p $PASSWORD --chroot=/
