# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
#alias openerp-client='/home/openerp/workspace/openerp-client/bin/openerp-client.py'
alias openerp-update.sh='openerp-updater.sh'
alias openerp-updater='openerp-updater.sh'
alias openerp-update='openerp-updater.sh'

PATH=$PATH:$HOME/bin

export PATH
 
