#!/bin/bash -ex

HOSTNAME=openerp6
# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.0.1 \(.*\)|127.0.0.1 localhost $HOSTNAME|" /etc/hosts
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

PSQLRELEASE=8.4
PYTHONRELEASE=python2.6
UBUNTURELEASE=10.04
INSTALLPATH=/usr/local
#SITEPACKAGESPATH=$INSTALLPATH/lib/$PYTHONRELEASE/site-packages
SITEPACKAGESPATH=$INSTALLPATH/lib/$PYTHONRELEASE/dist-packages
OPENERPSERVERPATH=$SITEPACKAGESPATH/openerp-server
ADDONSPATH=$OPENERPSERVERPATH/addons/   #/usr/local/lib/python2.6/dist-packages/openerp-server/addons/
OPENERPSERVERWRONGPATH=/nobugnoworkaround
MYDESKTOP=/home/openerp
PASSWVAR="openerp"
#OPENERPPASSWORD=$(mcookie)
OPENERPPASSWORD="openerp"
USER=openerp
STABLETRUNKLINK=6.0
STABLETRUNKVAR=6.0
RELEASE=6.0.3
PATH=/usr/bin:/sbin:/bin:/usr/sbin

apt-get update
############apt-get install -y gnupg
# BZR 2.0+ INSTALLATION (ubuntu 8.04 provides bzr 1.6)
# We are going to upgrade the repositories format to the 2a version. This will hopefully reduce the size of the checkout, speed up some operations and make it possible to use stacked branches reliably.
# From now on, Bazaar 2.0+ will be required to contribute to OpenERP. 
# http://julienthewys.blogspot.com/2010/02/code-repository-upgrade.html
#####echo "deb http://ppa.launchpad.net/bzr/ubuntu hardy main" >> /etc/apt/sources.list.d/sources.list
#####apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8C6C1EFD
#####apt-get update
#####apt-get update

echo "------------------------------------"
echo "Installing OPENERP"
echo "------------------------------------"

chown openerp.openerp /home/openerp/bin/openerp-updater.sh
chmod 740 /home/openerp/bin/openerp-updater.sh

cd /home/openerp/production/openerp-server
python setup.py install

cd /home/openerp/production/openerp-client
python setup.py install
cd /home/openerp/production/openerp-web
#easy_install -U openerp-web
## Comento siguiente línea por bug: https://bugs.launchpad.net/openobject-client-web/+bug/641428 :
###########################python setup.py install
# Finalmente lo dejo, he quitado la dependencia de Babel de setup.py (ver directorio overlay), ya lo tengo instalado
# con python-pybabel
python setup.py install
# Error que tenia por Babel:
#
#Searching for Babel==0.9.4
#Reading http://pypi.python.org/simple/Babel/
#Reading http://babel.edgewall.org/
#Reading http://babel.edgewall.org/wiki/Download
#Best match: Babel 0.9.4
#Downloading http://ftp.edgewall.com/pub/babel/Babel-0.9.4-py2.6.egg
#error: Can't download http://ftp.edgewall.com/pub/babel/Babel-0.9.4-py2.6.egg: 404 Not Found

mkdir -p $ADDONSPATH
#cp -ru /home/openerp/production/addons/* $ADDONSPATH
#cp -ru /home/openerp/production/extra-addons/* $ADDONSPATH
ln -sf /home/openerp/production/extra-addons/* $ADDONSPATH
ln -sf /home/openerp/production/addons/* $ADDONSPATH    # módulos más importantes y certificados, los últimos en enlazar (account_coda está duplicado en addons y extra-addons)
# ln without "--force"
# ln: creating symbolic link `/usr/lib/python2.5/site-packages/openerp-server/addons/base_module_merge': File exists

#if [ "$UBUNTURELEASE" = "9.10" -a -d $OPENERPSERVERWRONGPATH/addons ]; then
# Adding workaround for bug in /home/openerp/openerp-server/setup.py that puts import_xml.rng and base.sql into the wrong location
# cp -ru $OPENERPSERVERWRONGPATH/* $OPENERPSERVERPATH/
# chown -R openerp.root $ADDONSPATH
# chmod 755 $ADDONSPATH
#fi

chown -R openerp.root $ADDONSPATH

#####################
# Extending Open ERP
# To extend Open ERP you’ll need to copy modules into the addons directory. That’s in your server’s openerp-server directory (which differs between Windows, 
# Mac and some of the various Linux distributions and not available at all in the Windows all-in-one installer).
# You can add modules in two main ways – through the server, or through the client.
# To add new modules through the server is a conventional systems administration task. As rootuser or other suitable user, you’d put the module in the 
# addons directory and change its permissions to match those of the other modules.
# To add new modules through the client you must first change the permissions of the addonsdirectory of the server, so that it is writable by the server. 
# That will enable you to install Open ERP modules using the Open ERP client (a task ultimately carried out on the application server by the server software).
#
chmod 755 $ADDONSPATH
###########################################
# Document Management Permissions: http://openobject.com/forum/topic13021.html?highlight=ftp
#  chown openerp $INSTALLPATH/lib/$PYTHONRELEASE/site-packages/openerp-server
chown openerp $OPENERPSERVERPATH
#
#echo "# DON'T PRESS ACCEPT/OK !!. Adding openerp-server and openerp-web init scripts and config files";
#####################################################################################
# openerp-server init script
#####################################################################################
chmod 0755 /etc/init.d/openerp-server
#Create /var/log/openerp with proper ownership:
mkdir -p /var/log/openerp
touch /var/log/openerp/openerp.log
chown -R openerp.root /var/log/openerp/

# ubuntu 9.10:
#sed -i "s#/usr/bin/openerp-server#$INSTALLPATH/bin/openerp-server#g" /etc/init.d/openerp-server
#####################################################################################
# openerp-server config file
#####################################################################################
chown root.root /etc/openerp-server.conf
chmod 644 /etc/openerp-server.conf

sed -i "s/db_password =/db_password = $PASSWVAR/g" /etc/openerp-server.conf

#####################################################################################
# openerp-web init script and openerp-web.cfg
#####################################################################################
# cp /usr/lib/python2.5/site-packages/openerp_web-5.0.1_0-py2.5.egg/scripts/openerp-web /etc/init.d/
chmod 0755 /etc/init.d/openerp-web
#sed -i "s#/usr/bin/openerp-web#$INSTALLPATH/bin/openerp-web#g" /etc/init.d/openerp-web

chown root.root /etc/openerp-web.cfg
chmod 644 /etc/openerp-web.cfg
#Create /var/log/openerp-web.log with proper ownership:
mkdir -p /var/log/openerp-web
touch /var/log/openerp-web/access.log
touch /var/log/openerp-web/error.log
chown -R openerp.root /var/log/openerp-web/

#echo "# DON'T PRESS ACCEPT/OK !!. Updating RC Services";
#Now run following command to start the OpenERP Web automatically on system startup (Debian/Ubuntu):
update-rc.d openerp-server start 21 2 3 4 5 . stop 21 0 1 6 .
update-rc.d openerp-web start 70 2 3 4 5 . stop 20 0 1 6 .

#########################################################################################################
# FIREWALL:
#apt-get install -y ufw
#ufw enable
#ufw allow ssh
#ufw allow http
#ufw allow https
## OpenERP port (GTK client):
#ufw allow 8069/tcp 
## OpenERP port (GTK client):
#ufw allow 8070/tcp 
## Turnkeylinux Webconsole ports:
#ufw allow 12320/tcp 
#ufw allow 12321/tcp 
#ufw allow 12322/tcp 
#ufw allow 12323/tcp 

#/etc/init.d/openerp-server start
#/etc/init.d/openerp-web start

#################################################################################
# Apache Modules:
a2enmod ssl
# We enable openerpweb site after creating "/etc/apache2/sites-available/openerpweb" file (not available in Ubuntu8.04)
a2ensite openerpweb
a2enmod rewrite
a2enmod suexec
a2enmod include
a2enmod proxy
a2enmod proxy_http
a2enmod proxy_connect
a2enmod proxy_ftp
a2enmod headers

# VNC Server (no in ubuntu server)
# apt-get install -y vino (ó x11vnc)
#apt-get update
#apt-get -y upgrade
#apt-get clean

#Stop postgresql daemon
/etc/init.d/postgresql-$PSQLRELEASE stop

mv /home/openerp/bash_profile /home/openerp/.bash_profile
mv /home/openerp/bashrc /home/openerp/.bashrc

# Comando para cambiar el keyboard layout:
# dpkg-reconfigure console-data
# Debería preguntar qué layout se desea al instalar el paquete por primera vez
# sería bueno que se ejecutara al arrancar el appliance por primera vez
#apt-get install -y console-data
# De la siguiente manera logro que no me pregunte en la instalación, que use config. por defecto:

DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install console-data console-common

# Bug en console-data: 
#http://kubuntuforums.net/forums/index.php?topic=3095875.0
#UBUNTU HARDY: The error seems to be a typo in line 1158 of the console-setup.config file
##################sed -i "s/eval \`locale\`/eval \'locale\'/g" /var/lib/dpkg/info/console-setup.config

# add-apt-repository proporcionado por el sig paquete (no en ubuntu 8.04). Sirve para añadir repositorios fácilmente
#apt-get install -y python-software-properties

#apt-get install -y pgadmin3

#############################################################################
# Lo siguiente es necesario para instalar/compilar las VirtualBox Addons, necesarias para pantalla completa
# VBoxAddons: Montar el "CD" con "sudo mount /dev/cdrom /mnt" y ejecutar "cd /mnt;./VBoxLinuxAdditions-x86.run"
# Poner VirtualBox -> Pantalla -> Memoria Video = 128MB al menos, para tener resolución máx/pantalla completa
# kernel 2.6.24-27 cuando se instala turnkeylinux, kernel 2.6.24-28 tras actualizar ubuntu -> instalo headers para ambos:
#####apt-get install -y linux-kernel-devel linux-headers-2.6.24-27 linux-headers-2.6.24-28 build-essential 
#apt-get install -y linux-kernel-devel linux-headers-2.6.32-25 build-essential 
#apt-get install -y linux-headers-`uname -r`
# Para compilar el kernel en ubuntu lucid:
#apt-get install -y fakeroot build-essential crash kexec-tools makedumpfile kernel-wedge
#apt-get build-dep linux
#apt-get install -y git-core libncurses5 libncurses5-dev libelf-dev asciidoc binutils-dev
#apt-get install -y linux-headers-`uname -r`
apt-get clean
apt-get -y autoremove

####################
# http://doc.openerp.com/_sources/book/1/1_1_Inst_Config/1_1_Inst_Config_db_create.txt
# SuperAdmin password, para que pueda ser modificado desde la Web (en lugar del por defecto admin/admin) el fichero openerp-server.conf 
# debe tener permisos openerp:
chown openerp.openerp /etc/openerp-server.conf 
chown -R openerp.openerp /home/openerp/

# This is a fix for openerp-client bug https://bugs.launchpad.net/openobject-client/+bug/674231 
ln -s /usr/local/lib/python2.6/dist-packages/openerp_client-$RELEASE-py2.6.egg/openerp-client /usr/local/lib/python2.6/dist-packages/openerp-client
ln -s /usr/local/lib/python2.6/dist-packages/openerp_client-$RELEASE-py2.6.egg/share/pixmaps/openerp-client /usr/share/pixmaps/openerp-client          
ln -s /usr/local/lib/python2.6/dist-packages/openerp_client-$RELEASE-py2.6.egg/share/openerp-client /usr/share/openerp-client   