#!/bin/bash -ex

HOSTNAME=openerp6desktop
# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.0.1 \(.*\)|127.0.0.1 localhost $HOSTNAME|" /etc/hosts
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

PSQLRELEASE=8.4
PYTHONRELEASE=python2.6
UBUNTURELEASE=10.04
INSTALLPATH=/usr/local
#SITEPACKAGESPATH=$INSTALLPATH/lib/$PYTHONRELEASE/site-packages
SITEPACKAGESPATH=$INSTALLPATH/lib/$PYTHONRELEASE/dist-packages
OPENERPSERVERPATH=$SITEPACKAGESPATH/openerp-server
ADDONSPATH=$OPENERPSERVERPATH/addons/   #/usr/local/lib/python2.6/dist-packages/openerp-server/addons/
OPENERPSERVERWRONGPATH=/nobugnoworkaround
MYDESKTOP=/home/openerp
PASSWVAR="openerp"
#OPENERPPASSWORD=$(mcookie)
OPENERPPASSWORD="openerp"
USER=openerp
STABLETRUNKLINK=6.0
STABLETRUNKVAR=6.0
PATH=/usr/bin:/sbin:/bin:/usr/sbin

apt-get update
############apt-get install -y gnupg
# BZR 2.0+ INSTALLATION (ubuntu 8.04 provides bzr 1.6)
# We are going to upgrade the repositories format to the 2a version. This will hopefully reduce the size of the checkout, speed up some operations and make it possible to use stacked branches reliably.
# From now on, Bazaar 2.0+ will be required to contribute to OpenERP. 
# http://julienthewys.blogspot.com/2010/02/code-repository-upgrade.html
#####echo "deb http://ppa.launchpad.net/bzr/ubuntu hardy main" >> /etc/apt/sources.list.d/sources.list
#####apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8C6C1EFD
#####apt-get update
#####apt-get update

echo "------------------------------------"
echo "Installing OPENERP"
echo "------------------------------------"

chown openerp.openerp /home/openerp/bin/openerp-updater.sh
chmod 740 /home/openerp/bin/openerp-updater.sh

cd /home/openerp/production/openerp-server
python setup.py install

cd /home/openerp/production/openerp-client
python setup.py install
cd /home/openerp/production/openerp-web
#easy_install -U openerp-web
## Comento siguiente línea por bug: https://bugs.launchpad.net/openobject-client-web/+bug/641428 :
###########################python setup.py install
# Finalmente lo dejo, he quitado la dependencia de Babel de setup.py (ver directorio overlay), ya lo tengo instalado
# con python-pybabel
python setup.py install
# Error que tenia por Babel:
#
#Searching for Babel==0.9.4
#Reading http://pypi.python.org/simple/Babel/
#Reading http://babel.edgewall.org/
#Reading http://babel.edgewall.org/wiki/Download
#Best match: Babel 0.9.4
#Downloading http://ftp.edgewall.com/pub/babel/Babel-0.9.4-py2.6.egg
#error: Can't download http://ftp.edgewall.com/pub/babel/Babel-0.9.4-py2.6.egg: 404 Not Found

mkdir -p $ADDONSPATH
#cp -ru /home/openerp/production/addons/* $ADDONSPATH
#cp -ru /home/openerp/production/extra-addons/* $ADDONSPATH
ln -sf /home/openerp/production/addons/* $ADDONSPATH
ln -sf /home/openerp/production/extra-addons/* $ADDONSPATH
# ln without "--force"
# ln: creating symbolic link `/usr/lib/python2.5/site-packages/openerp-server/addons/base_module_merge': File exists

#if [ "$UBUNTURELEASE" = "9.10" -a -d $OPENERPSERVERWRONGPATH/addons ]; then
# Adding workaround for bug in /home/openerp/openerp-server/setup.py that puts import_xml.rng and base.sql into the wrong location
# cp -ru $OPENERPSERVERWRONGPATH/* $OPENERPSERVERPATH/
# chown -R openerp.root $ADDONSPATH
# chmod 755 $ADDONSPATH
#fi

chown -R openerp.root $ADDONSPATH

#####################
# Extending Open ERP
# To extend Open ERP you’ll need to copy modules into the addons directory. That’s in your server’s openerp-server directory (which differs between Windows, 
# Mac and some of the various Linux distributions and not available at all in the Windows all-in-one installer).
# You can add modules in two main ways – through the server, or through the client.
# To add new modules through the server is a conventional systems administration task. As rootuser or other suitable user, you’d put the module in the 
# addons directory and change its permissions to match those of the other modules.
# To add new modules through the client you must first change the permissions of the addonsdirectory of the server, so that it is writable by the server. 
# That will enable you to install Open ERP modules using the Open ERP client (a task ultimately carried out on the application server by the server software).
#
chmod 755 $ADDONSPATH
###########################################
# Document Management Permissions: http://openobject.com/forum/topic13021.html?highlight=ftp
#  chown openerp $INSTALLPATH/lib/$PYTHONRELEASE/site-packages/openerp-server
chown openerp $OPENERPSERVERPATH
#
#echo "# DON'T PRESS ACCEPT/OK !!. Adding openerp-server and openerp-web init scripts and config files";
#####################################################################################
# openerp-server init script
#####################################################################################
chmod 0755 /etc/init.d/openerp-server
#Create /var/log/openerp with proper ownership:
mkdir -p /var/log/openerp
touch /var/log/openerp/openerp.log
chown -R openerp.root /var/log/openerp/

# ubuntu 9.10:
#sed -i "s#/usr/bin/openerp-server#$INSTALLPATH/bin/openerp-server#g" /etc/init.d/openerp-server
#####################################################################################
# openerp-server config file
#####################################################################################
chown root.root /etc/openerp-server.conf
chmod 644 /etc/openerp-server.conf

sed -i "s/db_password =/db_password = $PASSWVAR/g" /etc/openerp-server.conf

#####################################################################################
# openerp-web init script and openerp-web.cfg
#####################################################################################
# cp /usr/lib/python2.5/site-packages/openerp_web-5.0.1_0-py2.5.egg/scripts/openerp-web /etc/init.d/
chmod 0755 /etc/init.d/openerp-web
#sed -i "s#/usr/bin/openerp-web#$INSTALLPATH/bin/openerp-web#g" /etc/init.d/openerp-web

chown root.root /etc/openerp-web.cfg
chmod 644 /etc/openerp-web.cfg
#Create /var/log/openerp-web.log with proper ownership:
mkdir -p /var/log/openerp-web
touch /var/log/openerp-web/access.log
touch /var/log/openerp-web/error.log
chown -R openerp.root /var/log/openerp-web/

#echo "# DON'T PRESS ACCEPT/OK !!. Updating RC Services";
#Now run following command to start the OpenERP Web automatically on system startup (Debian/Ubuntu):
update-rc.d openerp-server start 21 2 3 4 5 . stop 21 0 1 6 .
update-rc.d openerp-web start 70 2 3 4 5 . stop 20 0 1 6 .
# Desktop Appliance: elimino confconsole para evitar que salte tras ver antes lxdm/X11:
update-rc.d -f confconsole remove
#########################################################################################################
# FIREWALL:
#apt-get install -y ufw
#ufw enable
#ufw allow ssh
#ufw allow http
#ufw allow https
## OpenERP port (GTK client):
#ufw allow 8069/tcp 
## OpenERP port (GTK client):
#ufw allow 8070/tcp 
## Turnkeylinux Webconsole ports:
#ufw allow 12320/tcp 
#ufw allow 12321/tcp 
#ufw allow 12322/tcp 
#ufw allow 12323/tcp 

#/etc/init.d/openerp-server start
#/etc/init.d/openerp-web start

#################################################################################
# Apache Modules:
a2enmod ssl
# We enable openerpweb site after creating "/etc/apache2/sites-available/openerpweb" file (not available in Ubuntu8.04)
a2ensite openerpweb
a2enmod rewrite
a2enmod suexec
a2enmod include
a2enmod proxy
a2enmod proxy_http
a2enmod proxy_connect
a2enmod proxy_ftp
a2enmod headers

# VNC Server (no in ubuntu server)
# apt-get install -y vino (ó x11vnc)
#apt-get update
#apt-get -y upgrade
#apt-get clean

#Stop postgresql daemon
/etc/init.d/postgresql-$PSQLRELEASE stop

mv /home/openerp/bash_profile /home/openerp/.bash_profile
mv /home/openerp/bashrc /home/openerp/.bashrc

###########################################################################
# appliance v2
# Ubuntu Desktop: Gnome
# NOTA IMPORTANTE: ubuntu-desktop instala tb openoffice, pero la que tiene es la V2, no la V3 que añado en el post-overlay tras disponer del repositorio.
#############apt-get install -y ubuntu-desktop

#DEBIAN_FRONTEND=noninteractive apt-get -y \
#    -o DPkg::Options::=--force-confdef \
#    -o DPkg::Options::=--force-confold \
#    install ubuntu-desktop

#ALTERNATIVA A PROBAR: LXDE!
#####apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7992E892
#####apt-get update
#####apt-get update
#apt-get install -y lxde --> Sale el siguiente error:
#0 upgraded, 31 newly installed, 0 to remove and 1 not upgraded.
#Need to get 9181kB of archives.
#After this operation, 26.0MB of additional disk space will be used.
#WARNING: The following packages cannot be authenticated!
#  gpicview lxappearance lxde-settings-daemon lxde-common lxpanel lxsession-lite pcmanfm lxde
#E: There are problems and -y was used without --force-yes
#############apt-get install -y xorg
#############apt-get install -y dbus dbus-x11
# el siguiente error sale al arrancar gdm pq falta por instalar ubuntu-artwork
#There was an error loading the theme Human . Can't open file /usr/share/gdm/themes/Human/Human.xml
####apt-get install -y ubuntu-artwork
#http://wiki.lxde.org/en/Ubuntu
#############apt-get install -y --force-yes --install-recommends lxde
apt-get install -y lxde
# lubuntu-desktop instala synaptic y otros muchos paquetes interesantes, a must!:
apt-get install -y lubuntu-desktop
# gnome-control-center instala gnome-keyboard-properties, necesario para cambiar de keyboar layout:
apt-get install -y gnome-control-center
#The LXDE screen saver app requires that this directory exist or it returns annoying error messages:
#mkdir /usr/share/backgrounds (ya existe)
##########apt-get install -y --force-yes lxlauncher lxtask lxterminal
##########apt-get install -y --force-yes lxsession lxrandr lxnm
# en el repositorio de ubuntu 8.04 hardy, no está lxinput (para seleccionar el keyboard layout), pq es una release antigua de lxde (0.3, no la 0.5)
# En ubuntu 10.04 está lxde 0.5 + lxinput, etc.
# carga mucho la VM: apt-get install -y gnome-system-tools gnome-control-center
#####apt-get install -y system-config-printer-gnome gnome-system-tools zip network-manager network-manager-gnome
# quizas el sig. paquete sobre tras haber instalado el principal , gnome-system-tools
#####apt-get install -y language-selector
# gestor de paquetes (probablemente los haya instalado ya tras el gnome-system-tools)
#####apt-get install -y synaptic 
#####apt-get install -y update-manager
# otras aplicaciones ligeras de interés:
# gnumeric: hoja de cálculo ligera
# galculator: calculadora
# sylpheed: cliente de correo
# parcelite: clipboard, no disponible en ubuntu 8.04
# apt-get install -y gnumeric   (mejor la de openoffice)
#####apt-get install -y galculator sylpheed 
#parcelite

########################### para gnome-keyboard-properties: 
# No es compatible con lxde ó falta paquetes. No funciona gnome-keyboard-properties, del paquete gnome-control-center:
# apt-get install -y gnome-control-center
########################### 
# para el keyboard selector, pero no me funciona: 
#apt-get install -y fbxkb
# instalo kkbswitch
#apt-get install -y kkbswitch

# Comando para cambiar el keyboard layout:
# dpkg-reconfigure console-data
# Debería preguntar qué layout se desea al instalar el paquete por primera vez
# sería bueno que se ejecutara al arrancar el appliance por primera vez
#apt-get install -y console-data
# De la siguiente manera logro que no me pregunte en la instalación, que use config. por defecto:

DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install console-data console-common

# Bug en console-data: 
#http://kubuntuforums.net/forums/index.php?topic=3095875.0
# ubuntu hardy: The error seems to be a typo in line 1158 of the console-setup.config file
######################sed -i "s/eval \`locale\`/eval \'locale\'/g" /var/lib/dpkg/info/console-setup.config

# add-apt-repository proporcionado por el sig paquete (no en ubuntu 8.04). Sirve para añadir repositorios fácilmente
#apt-get install -y python-software-properties

# Otro repositorio de LXDE, mejor no utilizar
# Distribution Lubuntu uses LXDE as Desktop
# lubuntu no tiene repostorio para 8.04/hardy:
#https://launchpad.net/~lubuntu-desktop/+archive/ppa
#/etc/apt/sources.list.d/lubuntu.list
#deb http://ppa.launchpad.net/lubuntu-desktop/ppa/ubuntu YOURUBUNTU main 
#deb-src http://ppa.launchpad.net/lubuntu-desktop/ppa/ubuntu YOURUBUNTU main 

######apt-get install -y firefox 
apt-get install -y pgadmin3

# VNC Server (no in ubuntu server)
# It is important to remember that VNC does not provide a security mechanism other then the encrypted password.
# VNC en gdm: http://es.wikihow.com/conectarse-remotamente-a-la-pantalla-de-entrada-en-Ubuntu
###################################################################### PROVISIONAL: apt-get install -y vino 
# Otros servidores vnc:
#apt-get install -y x11vnc
#apt-get install -y vnc4server
#aptitude install -y tightvncserver
#apt-get install -y vnc4server xinetd

# bzr-explorer no funciona, instalo solo bzr-gtk:
apt-get install -y bzr-gtk 
#############################################################################
# Lo siguiente es necesario para instalar/compilar las VirtualBox Addons, necesarias para pantalla completa
# VBoxAddons: Montar el "CD" con "sudo mount /dev/cdrom /mnt" y ejecutar "cd /mnt;./VBoxLinuxAdditions-x86.run"
# Poner VirtualBox -> Pantalla -> Memoria Video = 128MB al menos, para tener resolución máx/pantalla completa
# kernel 2.6.24-27 cuando se instala turnkeylinux, kernel 2.6.24-28 tras actualizar ubuntu -> instalo headers para ambos:
#####apt-get install -y linux-kernel-devel linux-headers-2.6.24-27 linux-headers-2.6.24-28 build-essential 
#apt-get install -y linux-kernel-devel linux-headers-2.6.32-25 build-essential 
#apt-get install -y linux-headers-`uname -r`
# Para compilar el kernel en ubuntu lucid:
#apt-get install -y fakeroot build-essential crash kexec-tools makedumpfile kernel-wedge
#apt-get build-dep linux
#apt-get install -y git-core libncurses5 libncurses5-dev libelf-dev asciidoc binutils-dev
#apt-get install -y linux-headers-`uname -r`
apt-get clean
apt-get -y autoremove

# Desktop shortcuts: (se crean con permisos root, no con permisos openerp)
ln -s /usr/local/share/applications/openerp-*.desktop /home/openerp/Desktop/

# Fix to avoid having the error "GTK+ icon theme is not properly set" when logging in:
# http://ubuntuforums.org/archive/index.php/t-867964.html
##########mv /home/openerp/gtkrc-2.0 /home/openerp/.gtkrc-2.0

####################
# http://doc.openerp.com/_sources/book/1/1_1_Inst_Config/1_1_Inst_Config_db_create.txt
# SuperAdmin password, para que pueda ser modificado desde la Web (en lugar del por defecto admin/admin) el fichero openerp-server.conf 
# debe tener permisos openerp:
chown openerp.openerp /etc/openerp-server.conf 
chown -R openerp.openerp /home/openerp/