#!/bin/bash -ex

PSQLRELEASE=8.3
PASSWVAR="openerp"

echo "------------------------------------"
echo "Enabling ubuntu multiverse repository"
echo "------------------------------------"
APT_SOURCES=/etc/apt/sources.list.d
sed -i "/hardy multiverse/ s/# //" $APT_SOURCES/sources.list
sed -i "/hardy-updates multiverse/ s/# //" $APT_SOURCES/sources.list
sed -i "/hardy-security multiverse/ s/# //" $APT_SOURCES/security.sources.list
apt-get update
apt-get install -y python python-dev build-essential python-setuptools python-psycopg2 python-reportlab python-egenix-mxdatetime python-tz python-pychart python-pydot python-lxml python-libxslt1 python-vobject graphviz python-libxml2 python-imaging python-profiler;
# openerp-client requirements:
apt-get install -y python-gtk2 python-glade2 xpdf; 
# Matplotlib & hippocanvas still required by openerp-client (not listed as a dependency for the package):
apt-get install -y python-matplotlib python-hippocanvas;
# Required by openerp v6:
apt-get install -y python-yaml

# Ubuntu 8.04.3 LTS Server requires xauth binary to remotely display linux applications like openerp-client:
apt-get install -y xauth
# Installing zenity on Ubuntu Server for the updater
apt-get install -y zenity

#if [ "$UBUNTURELEASE" = "8.04" -o "$UBUNTURELEASE" = "9.10" ]; then
# To fix a new error "The required version of setuptools (>=0.6c11) is not available", march 11th 2010
#echo "# DON'T PRESS ACCEPT/OK !!. Installing setuptools >=0.6c11";
easy_install -U setuptools
#fi

#Postgres Database configuration:
# vi /etc/postgresql/8.3/main/pg_hba.conf
#Replace the following line:
    ## “local” is for Unix domain socket connections only
    #local all all ident sameuser
#with:
    ##”local” is for Unix domain socket connections only
    #local all all trust
#Please, note that "local all all md5" was set up in previous versions of this script, but database backup failed from openerp-web and
#openerp-client with this config (with an empty file as result)
sed -i 's/\(local[[:space:]]*all[[:space:]]*all[[:space:]]*\)\(ident[[:space:]]*sameuser\)/\1trust/g' /etc/postgresql/$PSQLRELEASE/main/pg_hba.conf

#Restart Postgres:
/etc/init.d/postgresql-$PSQLRELEASE start
#Create a user account called openerp with password “openerp” and with privileges to create Postgres databases:
# su postgres
#createuser openerp -P
#    Enter password for new role: (openerp)
#    Enter it again:
#    Shall the new role be a superuser? (y/n) n
#    Shall the new role be allowed to create databases? (y/n) y
#    Shall the new role be allowed to create more new roles? (y/n) n

sudo -u postgres createuser openerp --no-superuser --createdb --no-createrole 
sudo -u postgres psql template1 -U postgres -c "alter user openerp with password '$PASSWVAR'"

