# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
PATH=$PATH:$HOME/bin
alias openerp-client='/home/openerp/production/openerp-client/bin/openerp-client.py'

export PATH
unset USERNAME
 
