#!/bin/bash
# regenerate openerp5 postgres password

PASSWORD="openerp"	
# Si dejo la clave vacia, en teoria lo preguntara durante la instalacion gracias a 72pgsql-password
#PASSWORD=""

CONF=/etc/openerp-server.conf
sed -i "s/db_password =\(.*\)/db_password = $PASSWORD/g" $CONF

/usr/lib/di-live.d/??pgsql-password -u openerp -p $PASSWORD --chroot=/
