#!/bin/bash -e
# lxdm is stopped make the first boot init scripts visible
[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
#service lxdm stop # Does not work well , Feb 2011
# lxdm is controlled by the Upstart Startup Manager:
initctl stop lxdm

