#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}
DEPS="wget libaio1 bc ksh libasound2 libx11-6 libxext6 libxft2 libxi6 libxp6 libxtst6 libstdc++5"
install $DEPS

export TERM=rxvt
wget ftp://ftp.software.ibm.com/software/data/db2/express/Ubuntu/debs/x86/9.7.0/db2exc_9.7.0-8_i386.deb
dpkg -i db2exc_9.7.0-8_i386.deb
rm db2exc_9.7.0-8_i386.deb

HOSTNAME="dubuntutkl"
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

rm -rf /var/cache/apt/*
mkdir -p /var/cache/apt/archives/partial

